MV_SQLScriptCollector/src/scripts/models.py
from flask_login import current_user

from mixins import TimestampMixin
from src import db
from src.users.models import User


class Script(TimestampMixin, db.Model):

    __tablename__ = "scripts"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True, index=True)
    name = db.Column(db.String(length=64), unique=True, index=True, nullable=False)
    description = db.Column(db.String(length=128))
    code = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)
    user = db.relationship("User", back_populates="scripts", lazy="select")

    def __init__(self, name, description, code, user_id):
        self.name = name
        self.description = description
        self.code = code
        self.user_id = user_id

    def __repr__(self):
        return f"<Script {self.name}>"

# TODO реализовать обновление поля scripts_quantity, после добавления нового скрипта
# @db.event.listens_for(Script, "after_insert")
# def after_insert(mapper, connection, target):

MV_SQLScriptCollector/src/scripts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, validators
from wtforms.widgets.core import TextArea

from src.scripts.models import Script


def get_choices(users):
    all_users = users.query.all()
    return [(user.id, user.email) for user in all_users]


class AddScriptForm(FlaskForm):
    name = StringField("Название скрипта", [validators.Length(max=64), validators.DataRequired()])
    description = StringField("Описание скрипта", [validators.Length(max=128)])
    code = TextAreaField("Код скрипта", [validators.Length(max=4096), validators.DataRequired()],
                         widget=TextArea())
    user_id = SelectField("Автор SQL скрипта", [validators.Optional()])

    def validate(self, extra_validators=None):
        initial_validation = super(AddScriptForm, self).validate(extra_validators)
        if not initial_validation:
            return False
        script = Script.query.filter_by(name=self.name.data).first()
        if script:
            self.name.errors.append("Script already added")
            return False
        return True

MV_SQLScriptCollector/src/scripts/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user

from src import db
from src.scripts.models import Script

from src.scripts.forms import AddScriptForm
from src.users.models import User

scripts_bp = Blueprint("scripts", __name__,
                       template_folder="templates",
                       static_folder="static",
                       url_prefix="/scripts")


@scripts_bp.route("/", methods=["GET"])
@login_required
def scripts_list():
    title = "Список SQL скриптов - МВ проект 'Scripts DataBase' - Камила Титова"
    if current_user.is_authenticated:
        if current_user.allow_see_others:
            scripts = Script.query.all()
        else:
            scripts = Script.query.filter_by(user_id=current_user.id).all()
        return render_template('scripts/scripts_list.html', title=title, scripts=scripts)
    flash("You are not authenticated. Please login.", "danger")
    return render_template("core/index.html")


@scripts_bp.route("/add", methods=["GET", "POST"])
@login_required
def add_script():
    title = "Добавление SQL скрипта - МВ проект 'Scripts DataBase' - Камила Титова"
    if current_user.allow_add:
        form = AddScriptForm(request.form)
        users = User.query.all()
        form.user_id.choices = [[user.id, user.email] for user in users]
        if form.validate_on_submit():
            script = Script(name=form.name.data, description=form.description.data, code=str(form.code.data),
                            user_id=form.user_id.data)
            db.session.add(script)
            db.session.commit()
            flash(f"SQL script {form.name.data} was successfully added to DB", "success")
            return redirect(url_for("scripts.scripts_list"))
        return render_template("scripts/add_script.html", users=users, form=form)
    else:
        flash("You do not have permissions to add scripts.", "danger")
        return render_template("core/index.html")


@scripts_bp.route("/<int:slug>", methods=["GET"])
@login_required
def get_script(slug):
    if current_user.is_authenticated:
        if current_user.allow_see_others:
            script = Script.query.get(slug)
            return render_template("scripts/get_script.html", script=script)
        else:
            flash("You cannot view other users' scripts", "danger")
            return redirect(url_for("scripts.scripts_list"))
    return

MV_SQLScriptCollector/src/scripts/templates/scripts/add_script.html
{% extends "base.html" %}
{% block content %}
        <div class="row pt-3">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <main class="w-100 m-auto">
                    <form role="form" method="post" action="">
                        {{ form.csrf_token }}
                        <h1 class="h3 mb-3 fw-normal text-center">Добавление нового SQL скрипта</h1>
                        <div class="form-floating">
                            {{ form.name(placeholder="name", class="form-control mb-2") }}
                            {{ form.name.label }}
                            {% if form.name.errors %}
                                {% for error in form.name.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="form-floating">
                            {{ form.description(placeholder="description", class="form-control mb-2") }}
                            {{ form.description.label }}
                            {% if form.description.errors %}
                                {% for error in form.description.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="form-floating">
                            {{ form.user_id(placeholder="Автор SQL скрипта", class="form-control mb-2") }}
                            {{ form.user_id.label }}
                            {% if form.user_id.errors %}
                                {% for error in form.user_id.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="form-floating">
                            {{ form.code(placeholder="SQL script code", class="form-control mb-2",
                            style="height: 400px") }}
                            {{ form.code.label }}
                            {% if form.code.errors %}
                                {% for error in form.code.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <button class="w-100 btn btn-lg btn-primary" type="submit">Добавить скрипт</button>
{#                        <p class="text-center mt-3">Уже зарегистрировались?#}
{#                            <a href="{{ url_for('users.login') }}">Войдите в систему</a>#}
{#                        </p>#}
                    </form>
                </main>
            </div>
            <div class="col-md-4"></div>
        </div>
{% endblock %}

MV_SQLScriptCollector/src/scripts/templates/scripts/get_script.html
{% extends "base.html" %}
{% block content %}
        <div class="row pt-3">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <main class="w-100 m-auto">
                        <h1 class="h3 mb-3 fw-normal text-center">Просмотр SQL скрипта</h1>
                        <div class="form-floating">
                            <span class="form-control mb-2" id="floatingLabelName">{{ script.name }}</span>
                            <label for="floatingInput">Название скрипта</label>
                        </div>
                        <div class="form-floating">
                            <span class="form-control mb-2" id="floatingLabelName">{{ script.description}}</span>
                            <label for="floatingInput">Описание скрипта</label>
                        </div>
                        <div class="form-floating">
                            <span class="form-control mb-2" id="floatingLabelName">{{ script.user_id}}</span>
                            <label for="floatingInput">Автор скрипта</label>
                        </div>
                        <div class="form-floating">
                            <span class="form-control mb-2" id="floatingLabelName" style="height: 400px">{{ script.code}}</span>
                            <label for="floatingInput">Код скрипта</label>
                        </div>
                        <p class="w-100 btn btn-lg btn-primary">
                            <a class="text-white link-underline" href="{{ url_for('scripts.scripts_list') }}">Список скриптов</a>
                        </p>
                </main>
            </div>
            <div class="col-md-4"></div>
        </div>
{% endblock %}

MV_SQLScriptCollector/src/scripts/templates/scripts/scripts_list.html
{% extends 'base.html' %}
{% block content %}
    <main class="w-100">
        <div class="container pt-3">
            <h1 class="h3 mb-3 fw-normal text-center">Список SQL скриптов</h1>
            <table class="table table-sm table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Script name</th>
                        <th scope="col">Script description</th>
                        <th scope="col">UserID</th>
                        <th scope="col">Code</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for script in scripts %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>
                                <a href="{{ url_for('scripts.get_script', slug=script.id) }}">{{ script.name }}</a>
                            </td>
                            <td>
                                {{ script.description }}
                            </td>
                            <td>
                                {{ script.user_id }}
                            </td>
                            <td>
                                {% if script.code|length > 32 %}
                                    {{ script.code[:32] }}...
                                {% else %}
                                    {{ script.code }}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock %}